[ Feat] #367 차단/신고 뷰를 구현했습니다.
APPSCHOOL1-REPO/finalproject-gitspace pull request #371
Opened 2023-04-21 02:58 UTC by dahae0320

## 개요 및 관련 이슈
- 차단/신고 프로세스가 수행되는 뷰를 구현했습니다.
- #367 

## 작업 사항
- 차단/신고 프로세스를 수행할 수 있는 뷰 정리(이슈에 작성 완료)

#### View
- `BlockView`
- `ReportView`
- `SuggestBlockView`: 신고 후 차단할 지 물어보는 뷰

#### Enum
- `Report.ReportReasonDescription` 생성
    - ReportView에서 신고를 설명하기 위해 Enum을 새롭게 추가하였다.
    - Report와 연관을 짓고, 휴먼 에러를 줄이기 위해 Enum을 선택하였다.
- `Report.ReportReason`에 `CaseIterable` 프로토콜 추가
    - Enum이 가진 모든 값의 컬렉션을 제공할 수 있도록 하는 프로토콜이다.

#### Half Sheet
> iOS 15에는 Sheet의 크기를 설정할 수 없어서 Custom으로 구현하였다.
- `halfSheet`: halfSheet를 사용할 때 View의 수정자로 작성하면 된다.
    - View Extension에 구현되어 있다. 
    - TargetUserProfileView에서 사용 중이다.
- `HalfSheetManager`: 
- `CustomHostingController`: HostingController에서 UISheetPresentationController 사용

## 주요 로직(Optional)
#### 차단/신고 뷰 사용하기
> 차단/신고 뷰를 사용하려면 .halfSheet를 사용하면 된다. 사용법은 .sheet와 같다.

1. 차단/신고 모달이 나타나길 원하는 뷰에 `.halfSheet { .. }` 를 추가한다.
2. `.halfSheet`의 매개변수 `isPresented`, `content`를 채워준다.
    * 해당 뷰에 모달의 Appear을 조절할 바인딩 프로퍼티를 만들어 `isPresented`에 할당한다.
    * 모달로 띄우길 원하는 뷰를 `content`에 작성한다. 
    * **단, ReportView는 SuggestReportView도 같이 sheet로 만들어줘야 한다.**
3. 만약 dismiss 후 필요한 수행해야 하는 로직이 있다면 onDismiss에 값을 넣어주면 된다.

- 예시
```diff
struct TargetUserProfileView: View {
    // ...
    @State private var isBlockViewShowing = false
    @State private var isReportViewShowing = false
    @State private var isSuggestBlockViewShowing = false

    var body: some View {
        ScrollView(showsIndicators: false) { ... }
            .toolbar { ... }
           // BlockView
+          .halfSheet(isPresented: $isBlockViewShowing) {
+              BlockView(isBlockViewShowing: $isBlockViewShowing)
+          }
          // ReportView (위의 2개를 모두 해줘야 한다)
+          .halfSheet(isPresented: $isReportViewShowing) {
+              ReportView(isReportViewShowing: $isReportViewShowing, isSuggestBlockViewShowing: $isSuggestBlockViewShowing)
+         }
+          .halfSheet(isPresented: $isSuggestBlockViewShowing) {
+              SuggestBlockView(isBlockViewShowing: $isBlockViewShowing, isSuggestBlockViewShowing: $isSuggestBlockViewShowing)
+          }
    } //  body
}
```

#### BlockView
```swift
struct BlockView: View {
    @Binding var isBlockViewShowing: Bool
    var body: some View {
        VStack {
            // ...
            VStack {
                // ...
                HStack {
                    // Block 'No' Button
                    GSButton.CustomButtonView(style: .plainText(isDestructive: false)) {
                        isBlockViewShowing.toggle()
                    } label: {
                        Text("No")
                    }
                    // Block 'Yes' Button
                    GSButton.CustomButtonView(style: .secondary(isDisabled: false)) {
                        /* Block Method Call */
                        isBlockViewShowing.toggle()
                    } label: {
                        Text("Yes")
                    }
                }
            }
        }
    }
}
```

#### ReportView
```swift
struct ReportView: View {
    @Environment(\.dismiss) private var dismiss
    @Binding var isReportViewShowing: Bool
    @Binding var isSuggestBlockViewShowing: Bool
    // ...

    var body: some View {
        VStack {
            /* Report Title */
            /* Report Description */  
            /* Select Report Reason Description */
            /* Select Report Reason */
            ForEach(
                Array(zip(Report.ReportReason.allCases, (0...Report.ReportReason.allCases.count-1))),
                id:\.0
            ) { (reason, index) in
                Divider()
                VStack(alignment: .leading) { ... }
                    .contentShape(Rectangle())  /// HStack을 전부 탭 영역으로 잡기 위해 추가함.
                    .onTapGesture { ... }
                     /* Report Reason Description */
                    if (isReportReasonSelected && reportReasonNumber == index) { ... }
                }
            }
            Divider()
            
            /* Submit Report */
            GSButton.CustomButtonView(
                style: .secondary(isDisabled: isReportReasonSelected)
            ) {
                /* report method call */
                dismiss()
                isReportViewShowing.toggle()
                isSuggestBlockViewShowing.toggle()
            } label: {
                Text("Submit Report")
            }
            .padding()
            .disabled(!isReportReasonSelected) /// GSButton의 isDisabled이 작동하지 않아서 따로 수정자 붙임.
        }
    }
}

```

#### SuggestBlockView
특별한 부분이 없으므로 코드는 생략합니다.

#### View Extension: halfSheet
```swift
// MARK: - Half Sheet을 사용하기 위한 Extension
/// Half Sheet를 사용할 수 있는 View의 Extension이다.
/// iOS 15의 SwiftUI에서는 Sheet의 크기를 조절하는 API가 없다.
/// 그러므로 HalfSheetManager를 background에 사용하여 half modal을 구현한다.
func halfSheet<Content: View>(
  isPresented: Binding<Bool>,
  onDismiss: (() -> ())? = nil,
  @ViewBuilder content: @escaping () -> Content
) -> some View {
  return self
      .background {
           HalfSheetManager(
              isPresented: isPresented,
              onDismiss: onDismiss,
              content: content()
           )
      }
}
```

#### HalfSheetManager
```swift
struct HalfSheetManager<Content: View>: UIViewControllerRepresentable {
    @Binding var isPresented: Bool
    var onDismiss: (() -> ())?
    var content: Content
    let controller = UIViewController()

    func makeCoordinator() -> Coordinator {
        return Coordinator(parent: self)
    }

    func makeUIViewController(context: Context) -> UIViewController {
        controller.view.backgroundColor = .clear
        return controller
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        if isPresented {
            let sheetController = CustomHostingController(rootView: content)
            sheetController.presentationController?.delegate = context.coordinator
            uiViewController.present(sheetController, animated: true)
        } else {
            // choosing view when showsheet toggled againg
            uiViewController.dismiss(animated: true)
        }
    }
    
    // On dismiss
    class Coordinator: NSObject, UISheetPresentationControllerDelegate {
        var parent: HalfSheetManager

        init(parent: HalfSheetManager) {
            self.parent = parent
        }

        func presentationControllerDidDismiss(_ presentationController: UIPresentationController) {
            parent.isPresented = false
            if parent.onDismiss != nil {
                parent.onDismiss!()
            }
        }
    }
}
```

#### CustomHostingController
```swift
class CustomHostingController<Content: View>: UIHostingController<Content> {

    override func viewDidLoad() {
        view.backgroundColor = .systemBackground
        print(rootView)
        // setting presentation controller properties
        if let presentationController = presentationController as? UISheetPresentationController {
            
            switch rootView {
            case is ReportView:
                presentationController.detents = [
                    .large()
                ]
            default:
                presentationController.detents = [
                    .medium(),
                    .large()
                ]
            }
            // to show grab protion
            presentationController.prefersGrabberVisible = true
        }
    }
}
```

2023-04-21 14:55 UTC, ValseLee commented on GitSpace/Sources/Models/Report.swift
> +    enum ReportReasonDescription: String, CaseIterable {
Description의 case와 Reason의 case 이름 같아도 괜찮을까요?
호출하는 곳에서 혼동이 올 수도 있다는 의견입니다..!

2023-04-21 15:01 UTC, ValseLee commented on GitSpace/Utilities/Extensions/View+.swift
> +        onEnd: @escaping ()->()
이거 보니까 PR에는 onDismiss로 되어있네요? 코드가 뭔가 반영이 안된 걸지도?

2023-04-21 15:06 UTC, dahae0320 commented on GitSpace/Sources/Models/Report.swift
> +    enum ReportReasonDescription: String, CaseIterable {
Euem 이름이 다르니까 case는 동일해도 혼란스럽지 않을 거라고 생각했습니다. 그런데 생략해서 쓸 경우에는 승준님 말대로 충분히 혼란의 여지가 발생하겠네요. case에 'Description' 레이블을 추가하면 어떨까요?

2023-04-21 15:07 UTC, dahae0320 commented on GitSpace/Utilities/Extensions/View+.swift
> +        onEnd: @escaping ()->()
저도 이 부분에 동의해서 .sheet의 매개변수와 동일한 이름으로 수정해두었는데, PR에 올라가지 않은 모양입니다 :(
작업은 다 끝나 있어서 바로 push 해둘게요 !

2023-04-21 15:08 UTC, ValseLee commented on GitSpace/Sources/Models/Report.swift
> +    enum ReportReasonDescription: String, CaseIterable {
좋습니다
spammingDescription 등의 네이밍이면 혼동없이 케이스 호출이 될 것 같네요~

2023-04-21 15:08 UTC, ValseLee commented on GitSpace/Utilities/Extensions/View+.swift
> +        onEnd: @escaping ()->()
조아요 그 상단의 action {} label: {} 구조는 어떻게 생각하시나욧

2023-04-21 15:10 UTC, dahae0320 commented on GitSpace/Utilities/Extensions/View+.swift
> +        onEnd: @escaping ()->()
.sheet의 구조가 isPresented: onDismiss: {} content: {} 여서 이와 동일하게 수정해두었습니다. 반영된 코드가 올라갔을까요?

2023-04-21 15:12 UTC, ValseLee approved these changes
아주아주 좋습니당
추후에는 onDismiss의 함수 타입도 typealias 등으로 정리해서
가독성을 높이는 방향을 고려해보면 좋을 것 같군요
머지 Approve합니닷

2023-04-21 16:13 UTC, jekyun-park approved these changes

2023-04-21 16:13 UTC, jekyun-park commented on GitSpace/Sources/Models/Report.swift
>          case bullying = "Cyberbullying or Harassment"
```suggestion
        case bullying = "Cyberbullying or Harassment"
        
        func makeDescription() -> String {
            switch self {
            case .spamming:
                return "~~~ Description"
            case .offensive:
                return "~~~ Description"
            case .sexual:
                return "~~~ Description"
            case .cheating:
                return "~~~ Description"
            case .bullying:
                return "~~~ Description"
            }
        }
```
메서드를 사용한다면 description을 위한 새로운 열거형을 만들지 않고 이런 느낌으로 작성할 수 있을 것 같습니다 😁

2023-04-21 16:31 UTC, guguhanogu commented on GitSpace/Sources/Models/Report.swift
>          case bullying = "Cyberbullying or Harassment"
저도 제균님이 제안한 방법대로 메서드를 사용하면 좋을 것 같아요!
두 열거형이 서로 연관되어 있으니 하나의 열거형 안에서 메서드로 관리하는 게 유지보수 할 때에도 좋아보입니다!

2023-04-21 16:47 UTC, guguhanogu requested changes
다혜님 고생 많으셨습니다!
` SuggestBlockView ` 쪽 분기 처리만 해주시면 될 것 같습니다!

2023-04-21 16:47 UTC, guguhanogu commented on GitSpace/Sources/Models/Report.swift
>          case bullying = "Cyberbullying or Harassment"
저도 제균님이 제안한 방법대로 메서드를 사용하면 좋을 것 같아요!
두 열거형이 서로 연관되어 있으니 하나의 열거형 안에서 메서드로 관리하는 게 유지보수 할 때에도 좋아보입니다!

2023-04-21 16:47 UTC, guguhanogu commented on GitSpace/Sources/Views/Common/BlockView.swift
> +                        Text("Yes")
신고와 차단과 관련된 Yes 버튼의 텍스트 색상은 빨간색으로 하는 게 어떨까요?

2023-04-21 16:47 UTC, guguhanogu commented on GitSpace/Sources/Views/Common/SuggestBlockView.swift
> +                GSText.CustomTextView(style: .title3, string: "Well... Do you want to Block this user?")
이미 Block한 유저를 신고했을 경우에,
24번 라인 이후의 코드를 분기 처리 해줘야겠네요!

- 이미 Block한 유저라면
```suggestion
                GSButton.CustomButtonView(style: .plainText(isDestructive: false)) {
                    isSuggestBlockViewShowing.toggle()
                } label: {
                    Text("Ok")
                }
                .padding([.leading, .trailing], 20)
```
- Block하지 않은 유저라면
아래의 코드 진행

2023-04-22 14:20 UTC, wontaeyoung approved these changes

2023-04-22 14:20 UTC, wontaeyoung commented on GitSpace/Sources/Views/Common/BlockView.swift
> +                        Text("Yes")
차단이나 신고 자체가 부정적인 액션을 수행하긴 하지만, Alert 등 다른 SwiftUI에서 빨간색 버튼으로 제공하는 destructive가 데이터 삭제를 의미하는 경우가 있어서 고려가 필요해보입니다.

레퍼런스로 차단을 수행하는 다른 앱의 버튼을 확인했을 때, 검은색 텍스트로 제공하는 경우가 더 많기도 했습니다,

2023-04-22 14:43 UTC, guguhanogu approved these changes

2023-04-22 15:19 UTC, yeseul321 approved these changes
너무 완벽한 코드와 팀원들의 조화네요. 직관적인 코드 잘 봤습니다. 수고하셨어요 다혜님.

2023-04-23 14:05 UTC, lianne-b reviewed
버튼과 관련해선 태영님 의견에 동의합니다. 코드 잘 확인했습니다! 감사합니다 다혜님 :)

2023-04-23 14:07 UTC, lianne-b approved these changes

2023-04-23 14:27 UTC, merged